app.py
resources/DataSources.py

Simple endpoint that provides json output of data sources, with pre-approved columns so protected data is not returned. Requires authentication.

data sources endpoint w/ auth

---

client/.gitignore
client/globals.js
client/package-lock.json
client/package.json
client/src/components/QuickSearchForm.vue
client/src/main.js
client/src/pages/QuickSearchPage.vue
client/src/pages/SearchResultPage.vue
client/src/router.js
client/src/tests/SearchResultPage.test.js
client/vue.config.js

* Point frontend Vue app to the deployed API
* Update "county" term to "location" to reflect new quick search functionality
The frontend's BASE_URL for all requests to the API are pointing to the deployed API instead of a local server.

Update vue app

---

README.md
client/globals.js
client/public/index.html
client/src/pages/SearchResultPage.vue
client/src/router.js
client/vue.config.js

* Make the BASE_URL an env variable that can point to the respective live API based on whether it's the dev or main branch
I created an env variable that can point to either the dev or prod API depending on the env variable input.

Update BASE_URL for API endpoints

---

app_test.py
middleware/initialize_psycopg2_connection.py
requirements.txt
resources/QuickSearch.py

* Searching for a county name now work whether the word "county" is included or not
* Adds the word "county" to the string of each county name when doing check for matches. This will match submitted locations both with and without "county". Also adds pytest unit tests for to verify this is the case

county fix, tests

---

client/src/pages/DataSourceStaticView.vue
middleware/initialize_psycopg2_connection.py
requirements.txt
resources/DataSources.py

Update data sources by id endpoint to maintain separate data source and agency airtable uids to make sure the data source detail view populates properly

Airtable uid disambiguation

---

resources/QuickSearch.py

Added join on new state_names table so search location  can be checked against the full state name

full name state search

---

app_test.py
middleware/initialize_psycopg2_connection.py
resources/QuickSearch.py

retry matching with original search if spacy fails

Search retry

---

client/src/components/QuickSearchForm.vue
client/src/pages/QuickSearchPage.vue
resources/QuickSearch.py

Add option to search "all" for search term and location

Null searches

---

resources/QuickSearch.py

This PR is to address some changes made by issue #96. I removed a parenthesis that was causing an error and an unused column name.

Fix parenthesis error and remove unused column name

---

app_test.py
middleware/data_source_queries.py
middleware/quick_search_query.py

* Fix format available and date format for quick search and data sources endpoint results
Previously, data source results iterated over every letter of format available instead of iterating over each format. This fix will ensure that the data is formatted correctly for format available and make date formats consistent across all results as well.
N/A

Fix format available and date format for quick search and data sources

---

client/package-lock.json
client/package.json

update design system version

---

client/package-lock.json
client/package.json

[deployment](https://cloud.digitalocean.com/apps/a0991736-9273-4c0c-bc8d-73e42e6c64b9/deployments/77ab47da-bfe8-4e1a-a3de-d298a90f345e?i=feca0b) failed

updating package files

---

middleware/quick_search_query.py

url_status in quick search query

---

client/package-lock.json
client/package.json

design system `2.1.5` is live, small tweaks to quick search: https://github.com/Police-Data-Accessibility-Project/design-system/pull/38

bump design system

---

middleware/quick_search_query.py

if spacy returns less results, use original search

---

README.md

1. Remove data sources directory from your machine.
```
rm -rf path/to/your/local/data-sources
```
2. Follow the instructions in the `README` to re-clone and re-set up the application locally.
3. Ensure that navigating directly to [a search route with known data](http://localhost:5173/search/all/chicago) displays the expected loading state -> results.

docs(README): clarify local development setup

---

client/src/App.vue

should merge after https://github.com/Police-Data-Accessibility-Project/pdap.io/pull/166
merging straight to main because dev is a little crowded.

rename volunteer in nav

---

client/package-lock.json
client/package.json
client/src/App.vue
client/src/components/SearchResultCard.vue
client/src/pages/DataSourceStaticView.vue
client/src/pages/SearchResultPage.vue
client/src/pages/util.js
client/src/util/formatDate.js
client/tailwind.config.js

This will handle #150 when merged into `main`. Not marking as resolved as this PR goes to `dev`.
Run app locally, ensure that behavior and styling match requirements in #150. See screen recording below for successful demo.
https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/68428039/0562dd96-6187-4857-92e0-5cba706dc3a0

refactor: data source static view

---

client/src/pages/DataSourceStaticView.vue
client/src/pages/QuickSearchPage.vue
client/src/pages/SearchResultPage.vue
client/src/util/pluralize.js

refactor: update search more button

---

.github/workflows/tests.yml

Automated tests2

---

client/src/util/formatDate.js

When merged to `main`, this will take care of #146.

refactor: update date ranges

---

client/package-lock.json
client/package.json
client/src/pages/DataSourceStaticView.vue
client/src/pages/QuickSearchPage.vue
client/src/pages/SearchResultPage.vue
client/src/pages/__tests__/__snapshots__/app.test.js.snap
client/src/pages/__tests__/__snapshots__/dataSourceStaticView.test.js.snap
client/src/pages/util.js

Will take care of #197 when merged to `main`
Run the apps locally.
Visit http://localhost:5173/data-sources/rec1E18NmHrvE0UKh in one tab.
Visit https://data-sources.pdap.dev/data-sources/rec1E18NmHrvE0UKh in another tab.
Ensure they match visually and functionally.

feature: add tertiary button from design-system

---

app_test_data.py
middleware/archives_queries.py

remove agencies join from archives endpoint, change url_status when updating broken url

Archives endpoint updates to support url caching updates

---

client/package-lock.json
client/package.json
client/src/components/SearchResultCard.vue
client/src/components/__tests__/__snapshots__/searchResultCard.test.js.snap
client/src/pages/DataSourceStaticView.vue
client/src/pages/SearchResultPage.vue
client/src/pages/__tests__/__snapshots__/quickSearchPage.test.js.snap
client/src/pages/__tests__/__snapshots__/searchResultPage.test.js.snap
client/src/pages/__tests__/quickSearchPage.test.js
client/src/pages/__tests__/searchResultPage.test.js
client/src/util/pageData.js
client/vite.config.js

Will complete #185 when merged to `main`.
To test:
- Run the app.
- Ensure that the `QuickSearchForm` displays per updates described in #185.
- Search for data sources, ensure the search page displays per updates described in #185.

refactor: search results and quick search

---

app_test.py
middleware/data_source_queries.py

Very minor PR changing function name after it was mistakenly changed to the old function name. I did add "get_" to the function name just to add a little additional clarity.

Rename data_sources_results() to get_approved_data_sources()

---

app.py
app_test.py
middleware/data_source_queries.py
regular_api_checks.py
resources/DataSources.py
resources/SearchTokens.py

Resolves: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/240
Docs: https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/482/api/endpoints/data-sources-database

adding endpoint to support data sources map

---

.github/scripts/comment_pr.py
.github/workflows/python_checks.yml
.pydocstyle
README.md

* #213
* Implemented docstring checks through pydocstyle and added Python checks in Github Actions. 
* The Python checks include running `mypy` and `pydocstyle` on modified Python files and commenting the output on the associated pull request.
* It is designed to only run on files that have been modified in the pull request.
Testing has already been demonstrated in the following PRs:
* [This PR](https://github.com/maxachis/Github-Action-Test/pull/1#issuecomment-2043748474), which (after a few modifications) showcases how it would work on a PR
* [This other PR](https://github.com/maxachis/Github-Action-Test/pull/2), which shows it functioning again, but now _only on the new file I've created_. The other file, despite not being corrected, is not checked -- it only runs these checks on files …

Implement docstring checks and Python checks

---

.github/workflows/tests.yml
regular_api_checks.py
resources/SearchTokens.py

-All tests are passing in a normal state, adds discord notification when one is failing and the app needs fixing
-Prevent insert of search term in quick search logs for tests

notify on test failure

---

middleware/quick_search_query.py

remove quotes from search terms to prevent query errors

---

middleware/quick_search_query.py
resources/QuickSearch.py

function args switched, query for 'county' capitlization corrected

---

resources/Agencies.py
resources/ApiKey.py
resources/Archives.py
resources/DataSources.py
resources/Login.py
resources/PsycopgResource.py
resources/QuickSearch.py
resources/RefreshSession.py
resources/RequestResetPassword.py
resources/ResetPassword.py
resources/ResetTokenValidation.py
resources/SearchTokens.py
resources/User.py

* No issue; this is a quality-of-life improvement.
* The resources for Flask-Restful (in the `Resources` directory) have been refactored to inherit from a new base class, PsycopgResource, which handles initialization with a database connection. 
* The previous identical __init__ functions have been removed from inheriting classes.
* This change enhances code reusability and maintenance by centralizing common functionality across multiple resources, eliminating redundancy, and promoting a DRY (Don't Repeat Yourself) approach.
* Tests were performed using the `app_test.py` module, located in the root directory.
* By simply modifying inheritance to a base class, performance impacts are marginal.
* No applicable documentation changes necessary.

Refactor resources to inherit from PsycopgResource base class

---

client/src/components/SearchResultCard.vue

Removes deprecated grid item component and replaces with a div

fix: remove GridItem

---

README.md

an update to the readme un-v2ifying

update dev from main

---

database_client/database_client.py
middleware/primary_resource_logic/data_sources_logic.py
tests/integration/test_data_sources.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/645
* fix bug causing approval status filter to not work

fix(api): fix bug causing approval status filter to not work

---

database_client/database_client.py
middleware/primary_resource_logic/admin.py
resources/Admin.py
resources/endpoint_schema_config.py
tests/helper_scripts/helper_classes/RequestValidator.py
tests/integration/test_admin.py

* Supports https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/612
* add endpoint  for admins to delete users
* Confirm tests run as expected
* New endpoint has about the same costs as creating a user
* New endpoint added in API

feat(app): add endpoint  for admins to delete users

---

alembic/versions/2025_03_10_1754-e8897f1ae7fb_further_overhaul_notification_logic.py
conftest.py
database_client/DTOs.py
database_client/database_client.py
database_client/models.py
middleware/enums.py
middleware/primary_resource_logic/github_issue_app_logic.py
middleware/schema_and_dto_logic/primary_resource_schemas/github_issue_app_schemas.py
middleware/third_party_interaction_logic/github_issue_api_logic.py
resources/GithubDataRequests.py
resources/endpoint_schema_config.py
tests/alembic/test_alembic_migrations.py
tests/helper_scripts/helper_classes/RequestValidator.py
tests/helper_scripts/helper_classes/TestDataCreatorDBClient.py
tests/integration/test_github_data_requests_issues.py
tests/integration/test_notifications.py

* Supports https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/299
* Revise notification logic in the backend to ensure better functionality with fewer untestable triggers 
* Revise GitHub Issue logic so that synchronize both adds ready issues to GitHub and updates them in the database.
* Remove `/github/data-requests/issues/{data_request_id}` endpoint
* Synchronize overhead increased.
* Trigger overhead in database reduced
* What functionality, if any, might be broken by this change, which could impact other developers. For example, an environmental variable changing.

feat(app): revise notification logic and refine github issue logic

---

ENV.md
alembic/versions/2025_03_11_0937-018aeb44ca51_add_github_issue_info_to_data_requests.py
middleware/third_party_interaction_logic/github_issue_api_logic.py

* Supports https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/299#issue-2314400158
* add missing github issue urls to existing data requests

feat(database): add missing github issue urls to existing data requests

---

middleware/primary_resource_logic/notifications_logic.py
tests/middleware/test_notification_logic.py

* Supports https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/26#issuecomment-2715164792
* correct data request URL for notifications
* No performance impact 

fix(app): correct data request URL for notifications

---

ENV.md
database_client/DTOs.py
database_client/database_client.py
middleware/primary_resource_logic/github_issue_app_logic.py
middleware/third_party_interaction_logic/github_issue_api_logic.py
tests/integration/test_github_data_requests_issues.py
tests/middleware/test_github_issue_api_logic.py
tests_manual/test_get_github_issue_project_statuses.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/299
* Fix bug relating to environment variable use. Bug fix and needed environment variables clarified.
* Run tests and confirm proper functionality
* ENV.md updated

fix(app): fix bug in github issue api logic

---

alembic/versions/2025_03_13_1132-7bcc381f0344_migrate_pdap_response_and_internal_.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/665
* Add missing pdap responses and internal notes

fix(database): Add missing pdap responses and internal notes

---

middleware/schema_and_dto_logic/primary_resource_schemas/data_sources_base_schemas.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/661
* set `/data-sources` `POST` name parameter to required
* No performance impact
* API documentation changed to reflect requirement

fix(api): set `/data-sources` `POST` name parameter to required

---

.github/workflows/run_pytest.yml
ENV.md
config.py

- https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/671
I thought I'd try this just for fun. However, I don't know how to predict what the result of `os.environ.get('ENVIRONMENT') `should be, and used "production" as a placeholder:
```
is_production = os.environ.get('ENVIRONMENT') == 'production'
```
Would be open to hearing whether this is a sound approach, or if we should address it some other way!
OAuth should use dev for anything but prod deployment!
no
no
this will only break things if it's not right

fix: oauth env

---

.github/workflows/run_pytest.yml
ENV.md
config.py

Reverts Police-Data-Accessibility-Project/data-sources-app#672

Revert "fix: oauth env"

---

ENV.md
database_client/DTOs.py
database_client/database_client.py
manual_tests/test_get_github_issue_project_statuses.py
middleware/primary_resource_logic/github_issue_app_logic.py
middleware/third_party_interaction_logic/github_issue_api_logic.py
tests/integration/test_github_data_requests_issues.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/299
* Add label synchronization to GitHub 
* Run tests to confirm all pass
* Increased overhead for GitHub sync

feat(app): add label-record type synchronization to github issue sync

---

database_client/database_client.py
database_client/result_formatter.py
local_database/README.md
middleware/schema_and_dto_logic/primary_resource_schemas/locations_schemas.py
resources/endpoint_schema_config.py
tests/integration/test_locations.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/681
* add `display_name` to `locations/{id}` `GET`
* Ensure all tests run as expected
* API documentation updated

fix(api): add display_name to `locations/{id}` `GET`

---

middleware/schema_and_dto_logic/primary_resource_schemas/data_sources_advanced_schemas.py
start_mirrored_local_app.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/688
* Add rejection notes to `/data-sources` `PUT`
* API documentation for  `/data-sources` `PUT` added to include `rejection_notes`

feat(api): Add rejection notes to `/data-sources` `PUT`

---

ENV.md
manual_tests/test_send_signup_link.py
middleware/primary_resource_logic/signup_logic.py
tests/integration/test_data_sources.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/684
* Fix HTML presentation in signup emails
* `ENV.md` updated to include mention of `TEST_EMAIL_ADDRESS`

fix(app): Fix HTML presentation in signup emails

---

database_client/result_formatter.py
tests/helper_scripts/helper_classes/TestDataCreatorFlask.py
tests/integration/test_agencies.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/697
* fix bug in `/agencies` `GET`
* Bug was causing errors when Federal agencies were included.
* Run tests and confirm all pass 
* Slight increase in test overhead

fix(database): fix bug in `/agencies` `GET`

---

middleware/schema_and_dto_logic/primary_resource_schemas/data_sources_base_schemas.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/703
* Remove required for `/data-sources` `POST` `description` attribute
* No performance impact
* API documentation updated

fix(api): Remove required for `/data-sources` `POST` `description` attribute

---

alembic/versions/2025_04_04_0841-f001f28e8ab2_add_source_collector_final_review.py
middleware/alembic_helpers.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/710
* add `source_collector_final_review` permission

feat(database): add `source_collector_final_review` permission

---

alembic/versions/2025_04_05_1620-d7634d1796d7_add_data_source_post_permission.py
app.py
database_client/database_client.py
database_client/models.py
middleware/enums.py
middleware/primary_resource_logic/github_issue_app_logic.py
middleware/primary_resource_logic/source_collector_logic.py
middleware/schema_and_dto_logic/primary_resource_dtos/source_collector_dtos.py
middleware/schema_and_dto_logic/primary_resource_schemas/source_collector_schemas.py
resources/SourceCollector.py
resources/endpoint_schema_config.py
tests/helper_scripts/common_endpoint_calls.py
tests/helper_scripts/helper_classes/RequestValidator.py
tests/helper_scripts/helper_classes/TestDataCreatorDBClient.py
tests/helper_scripts/helper_classes/TestDataCreatorFlask.py
tests/helper_scripts/helper_functions_complex.py
tests/integration/test_source_collector.py
utilities/namespace.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/713
* Create `/source-collector/data-sources` endpoint, which is designed to receive data sources in batches directly from the source collector
* Also makes some adjustments to test data generation and removal
* Run tests and confirm all function as expected
* New endpoint with distinct performance demands
* Increase in test overhead
* Documentation for new endpoint added to API documentation

Mc 713 data source post permission

---

alembic/versions/2025_04_23_1622-787dbb5518e8_add_lat_and_lng_to_locations_endpoint.py
app.py
database_client/database_client.py
middleware/primary_resource_logic/locations_logic.py
middleware/schema_and_dto_logic/primary_resource_schemas/locations_schemas.py
tests/integration/test_locations.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/729
* Include `state_iso` on state objects
* Remove `data_source_count` and associated logic.
* `/map/locations` documentation revised
* `/map/locations` endpoint modified per above.

feat(app): refine `/map/locations`

---

alembic/versions/2025_04_23_1622-787dbb5518e8_add_lat_and_lng_to_locations_endpoint.py
alembic/versions/2025_04_28_1810-30c3f217d58d_create_notification_log_table_and_.py
alembic/versions/2025_04_29_1235-682dbaf958b3_add_full_display_name_to_.py
database_client/database_client.py
database_client/models.py
middleware/enums.py
middleware/primary_resource_logic/metrics_logic.py
middleware/primary_resource_logic/notifications_logic.py
middleware/schema_and_dto_logic/common_fields.py
middleware/schema_and_dto_logic/common_schemas_and_dtos.py
middleware/schema_and_dto_logic/primary_resource_dtos/metrics_dtos.py
middleware/schema_and_dto_logic/primary_resource_schemas/metrics_schemas.py
resources/Metrics.py
resources/endpoint_schema_config.py
tests/conftest.py
tests/helper_scripts/helper_classes/MultiAgencySetup.py
tests/helper_scripts/helper_classes/MultiDataSourceSetup.py
tests/helper_scripts/helper_classes/MultiFollowSetup.py
tests/helper_scripts/helper_classes/MultiLocationSetup.py
tests/helper_scripts/helper_classes/MultiRequestSetup.py
tests/helper_scripts/helper_classes/MultiUserSetup.py
tests/helper_scripts/helper_classes/RequestValidator.py
tests/integration/test_metrics.py
tests/integration/test_notifications.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/738
* Add `/metrics/followed-searches` endpoints
* Run tests and confirm all perform as expected
* Increase in test overhead
* New API documentation for `/metrics/followed-searches/aggregate` `GET` and `/metrics/followed-searches/breakdown` `GET`

Mc 738 metrics followed searches

---

alembic/versions/2025_05_07_1324-e3d0a9476c73_update_map_counties_materialized_view.py
database_client/database_client.py
middleware/schema_and_dto_logic/primary_resource_schemas/locations_schemas.py
tests/integration/test_locations.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/751
* add county fips to `/map/locations` `GET`
* Performance impact marginal
* API documentation for `/map/locations` `GET` updated

feat(app): add county fips to `/map/locations` `GET`

---

alembic/versions/2025_05_09_1039-60e9d755ef82_update_map_localities_to_include_state_.py
database_client/database_client.py
middleware/schema_and_dto_logic/primary_resource_schemas/locations_schemas.py
tests/integration/test_locations.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/755
* Add county fips and state to `/map/locations/` `localities`
* Confirm tests ran successfully
* Materialized View for `map_localities` updated to include two additional columns

feat(api): Add county fips and state to `/map/locations/` `localities`

---

alembic/versions/2025_05_09_1543-7b0b4eaa9764_increase_data_request_title_character_.py
middleware/schema_and_dto_logic/primary_resource_schemas/data_requests_base_schema.py
middleware/schema_and_dto_logic/primary_resource_schemas/data_requests_schemas.py
tests/integration/test_data_requests.py

https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/760

Mc 760 data request title length

---

alembic/versions/2025_05_09_1624-f4773c5636a8_add_data_request_to_change_log.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/759
* Steps to test this PR, if there are any required.
* For cut-and-dry changes (API updates or interface tweaks), include a screenshot or updated API response to show what correct behavior looks like
* If you're adding or heavily modifying a script, estimate how long it should take to run.
* Accompanying docs PRs, if applicable
* What functionality, if any, might be broken by this change, which could impact other developers. For example, an environmental variable changing.

mc_759_data_requests_to_change_log

---

manual_tests/test_github_logic.py
manual_tests/test_synchronize_manual.py
middleware/third_party_interaction_logic/github_issue_api_logic.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/757
* A brief description of what this does. Include screenshots, if anything should change visually.
* Steps to test this PR, if there are any required.
* For cut-and-dry changes (API updates or interface tweaks), include a screenshot or updated API response to show what correct behavior looks like
* If you're adding or heavily modifying a script, estimate how long it should take to run.
* Accompanying docs PRs, if applicable
* What functionality, if any, might be broken by this change, which could impact other developers. For example, an environmental variable changing.

Mc 757 data requests sync bug

---

alembic/versions/2025_06_06_0909-8f26c4cc4c35_add_national_location_type_and_instance.py
database_client/enums.py
database_client/models/types.py
middleware/alembic_helpers.py
middleware/primary_resource_logic/match_logic.py
middleware/schema_and_dto_logic/primary_resource_schemas/locations_schemas.py
middleware/schema_and_dto_logic/primary_resource_schemas/typeahead_suggestion_schemas.py
resources/Match.py
resources/endpoint_schema_config.py
tests/integration/test_agencies.py
tests/integration/test_locations.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/767
* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/774
* https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/776
* https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/769

mc_774_allow_federal_follows

---

db/queries/instantiations/source_collector/sync.py
endpoints/instantiations/source_collector/sync/dtos/response.py
tests/integration/source_collector/test_sync.py

* https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/315
* Corrects bug in agency sync that erroneously provided location display name rather than agency display name
* Updated test to check for correct behavior

mc_775_record_category_follow

---

app.py

Helps close https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/423

link to api tos

---

alembic/versions/2025_07_14_1039-0896cefcf910_rework_list_database_columns.py
db/models/helpers.py
db/models/implementations/core/data_source/core.py
endpoints/instantiations/source_collector/data_sources/post/dtos/request.py
endpoints/instantiations/source_collector/data_sources/post/schemas/request.py
middleware/schema_and_dto/dtos/data_sources/base.py
tests/helper_scripts/complex_test_data_creation_functions.py
tests/integration/source_collector/data_sources/test_post.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/809
* Adjust list db columns to be `not null` and default to an empty list, and adjust all existing null values in these columns to be empty lists.

Adjust list db columns

---

endpoints/instantiations/map/data/schema.py
endpoints/instantiations/map/locations/queries/federal.py

* Supports https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/836
* Adds `source_id` value to `map/data` endpoint for `federal` results.
* Endpoint documentation updated

Add source id

---

apply_migrations.py
local_database/DataDumper/docker-compose.yml
local_database/constants.py
mirrored_local_app/DockerContainer.py
mirrored_local_app/constants.py
mirrored_local_app/docker_client.py
mirrored_local_app/docker_manager.py
mirrored_local_app/main.py
mirrored_local_app/models/docker.py

This is to enable testing the app locally before pushing changes to the dev environment.

mc_820_remove_unused_url_status

---

db/dynamic_query_constructor.py
middleware/scheduled_tasks/manager.py

* #856
* Update logic for search query to handle cases where a data source is associated with multiple localities
* Adds a print statement when refreshing a materialized view, for better transparency of logic.
* Run tests and confirm expected functionality.
* Revise search query is considerably faster -- for full details, see #856 

mc_856_result_count_discrepancies

---

endpoints/instantiations/source_collector/meta_urls/post/dtos/response.py
endpoints/instantiations/source_collector/meta_urls/post/enums.py
endpoints/instantiations/source_collector/meta_urls/post/queries/core.py
tests/integration/source_collector/meta_urls/test_post.py

* Issues being closed by this PR
* A brief description of what this does. Include screenshots, if anything should change visually.
* Steps to test this PR, if there are any required.
* For cut-and-dry changes (API updates or interface tweaks), include a screenshot or updated API response to show what correct behavior looks like
* If you're adding or heavily modifying a script, estimate how long it should take to run.
* Accompanying docs PRs, if applicable
* What functionality, if any, might be broken by this change, which could impact other developers. For example, an environmental variable changing.

Add agency ID as return value in `/source-collector/meta-urls` `POST`
