resources/DataSources.py

* Add missing "agency_name" column to for the data_source_matches returned
The Data Sources route was getting the agency_name value, but it wasn't included as a column in the data returned to the client.

Add column name for agency_name in return data

---

app.py
resources/Agencies.py

* Add pagination to agencies endpoint
* Limits each request to the agencies endpoint to 1000 and requires a "page" parameter which can be used to get more results in further requests
* Will update Gitbook with instructions on pagination usage

add pagination for agencies

---

middleware/security.py

* Enable API to accept a JWT token or API key for authorization
I added a check for an API key if there's an error raised for the JWT token decoder.

Add ability to get API key directly from user

---

client/src/pages/DataSourceStaticView.vue

* Remove repeating info in data source static view by removing second for loop
* Previously, the data source details page displayed the same information for a data source multiple times. Now, the page should display all the information once.

Fix repeating info in data source static view

---

client/src/components/SearchResultCard.vue

- removes button to view data source details (#151)
- dims "view source url" button if a source has no URL or url_status is `none found` or `broken`

final launch refinements → dev

---

resources/SearchTokens.py

Prod data sources app stopped returning results, in the runtime logs it looks like the db connection started to error after an insert of the search token. Currently we are not querying for search tokens so commenting this insert out for now

remove search token insert

---

client/src/pages/DataSourceStaticView.vue
resources/SearchTokens.py

found two instances of `VUE_APP_BASE_URL` when we should now be using `VITE_VUE_APP_BASE_URL` (I think)

base URL envar name

---

client/src/pages/SearchResultPage.vue
client/src/pages/__tests__/__snapshots__/searchResultPage.test.js.snap

1. Run the app locally.
2. Navigate to [`/search/health/allegheny`](http://localhost:8888/search/health/allegheny)
3. Ensure 3 records are displayed (in contrast to [the same route in prod](https://data-sources.pdap.io/search/health/allegheny), which currently shows 1).

fix(pages): update search results filtering

---

client/src/router.js

Will handle #199 when merged.
Run the app, visit several different routes, ensure that the tags change as expected per route (only the `og:url` tag will change for now, but we can use the `meta` property on the routes object to update others if need be)

feat(router): add logic to router to handle meta tags

---

client/src/pages/SearchResultPage.vue
client/src/pages/__tests__/__snapshots__/searchResultPage.test.js.snap
client/src/router.js

Resolving conflicts in the client on `dev` (resulting from multiple PRs merging directly to `main`) before any in-progress work makes them worse 😅

chore: main -> dev

---

middleware/login_queries.py

* #230
* Likely a product of my earlier refactorings, the parameter `user_id` was not being passed to the `sub` entry in `create_session_token()` -- instead, `id` was used, which is a specific python function. This has been corrected.
* Run app_test.py, with `SECRET_ENV` environment key properly filled in.

Rename id to user_id, matching parameter name.

---

app.py
client/src/pages/ResetPassword.vue
client/src/pages/SearchResultPage.vue
client/src/pages/__tests__/__snapshots__/resetPassword.test.js.snap
client/src/pages/__tests__/__snapshots__/searchResultPage.test.js.snap
client/src/pages/__tests__/resetPassword.test.js
client/src/stores/user.js
regular_api_checks.py
resources/RequestResetPassword.py
resources/ResetTokenValidation.py

Addresses [#214](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/214)
Reset tokens are now valid for 15 min, password reset email lists this fact
/reset-token-validation endpoint will check the reset token
Docs: https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/479/api/endpoints/admin

Improved password reset

---

README.md
middleware/data_source_queries.py

* Bug reported in PR #228 where type hinting caused error on pre-3.10 versions of Python.
* Replaces `|` type hint with `Union` type hint.
* Run app to confirm functionality on pre-3.10 version of Python.

Mc fix type hinting bug

---

client/src/pages/SearchResultPage.vue
client/src/pages/__tests__/__snapshots__/searchResultPage.test.js.snap

fixes #294 
now, this note about making a request will always show, regardless how many results appear. before, it wasn't showing when there were 0 results.

shuffle results messaging

---

app.py
middleware/homepage_search_cache.py
resources/HomepageSearchCache.py

* Partially addresses https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/53
- Added new middleware file `homepage_search_cache.py` to handle caching of search results for agencies without homepage URLs
- Added SQL queries to retrieve agencies without homepage URLs and update the search cache
- Implemented functions to get agencies without homepage URLs and update search cache
- Added new resource `HomepageSearchCache` in `resources/HomepageSearchCache.py` to handle API requests for retrieving and updating search cache
* Not sure! I could set up an integration test for it, or we could deploy it and see if it works/doesn't break things when I reconfigure the data source identification code to work with it, or try some unknown third option.
* Creation of …

⚡️ feat(middleware): Add functionality to cache homepage search results

---

README.md

adds a sample .env file for clarity on what we need to run the app. 
Used in `automatic_archives` but not here: `VUE_APP_PDAP_API_KEY`
Definitely deprecated: `VUE_APP_PDAP_TOKEN` (not used anywhere)

update sample .env file in readme

---

client/src/components/SearchResultCard.vue
middleware/initialize_psycopg2_connection.py

Fixes #338
`client/src/components/SearchResultCard.vue`
- javascript window.open() method assumes that without http(s):// it's a relative path. So this checks source_url and prepends https:// if not found.
`middleware/initialize_psycopg2_connection.py`
- explicitly load .env variables with dotenv

Malformed url bug fix

---

client/src/util/pageData.js

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/348
* Added two missing categories to `pageData.js`: `Media Bulletins` and `Other`
* A new header `Other` is used for `Other` record types, `Media Bulletins` is grouped under `Agency-published resources`
* Checkout the branch and setup testing environment like normal
* Search for and confirm previously unshown data sources are now shown on the results page

Fix quick search not showing all results - v1 patch

---

middleware/quick_search_query.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/346
* The quick search terms were previously case sensitive, causing some results to be excluded
* Removes `.title()` function that was previously applied to the search terms
* Changes the SQL query from `LIKE` to `ILIKE` (case-insensitive `LIKE`)
* `ILIKE` is a PSQL keyword similar to using `UPPER()` or `LOWER()` for case insensitive matching in other SQL versions. Read more about it here: https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-LIKE
* Checkout the branch
* Setup testing environment like normal
* Search using terms outlined in issue [346](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/346) and confirm the results are now returned properly

Fix quick search casing issue - v1 patch

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

fixes #402 
merging to main because it shouldn't affect anything downstream
looks like technically I did it the legacy way, but it should still work: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

Add templates

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

- removes h1 at the start
- consistent h3 headings
This is not product related so I'm not making an issue 👀

tweak templates

---

.github/workflows/run_pytest.yml
resources/Archives.py
tests/integration/test_archives.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/361
* `/archives` `PUT` request previously required the body to be loaded as a json string, rather than just as json. This has been fixed.
* API documentation for `/archives` `PUT` modified to remove warning to use json string
* This does technically break `/archives` `PUT`.
* However, nothing but the archives repository (which is currently broken) uses this, and the prior method was not the correct way of doing it in the first place.

Mc 361 streamline archives put data retrieval

---

middleware/schema_and_dto_logic/primary_resource_schemas/archives_schemas.py
tests/helper_scripts/helper_classes/RequestValidator.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/649
* adjust /archives GET last_archived_before query parameter to accept YYYY-MM-DD format
* No documentation change
* This does technically break `/archives` `GET`, but only the Archiver is using that, and it will be addressed shortly.

fix(api): adjust `/archives` `GET` last_archived_before to accept `YYYY-MM-DD` format

---

alembic/versions/2025_03_15_1634-75d2ecaaa93f_add_github_sync_permission.py
middleware/enums.py
middleware/primary_resource_logic/permissions_logic.py
middleware/schema_and_dto_logic/primary_resource_schemas/github_issue_app_schemas.py
resources/GithubDataRequests.py
tests/helper_scripts/helper_functions_complex.py
tests/integration/test_github_data_requests_issues.py

* Supports https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/299#issuecomment-2405951278
* Add `github_sync` permission for users
* Set up `/github/data-requests/synchronize` to require a user with `github_sync` permission.
* `/github/data-requests/synchronize` now requires `github_sync` permission.

feat(api): add permission for github_sync

---

alembic/versions/2025_03_31_1052-2f6972890d82_update_typeahead_agencies_view_to_.py
alembic/versions/2025_03_31_1630-c1d862a9a587_add_creator_user_id_to_agencies.py
app.py
database_client/database_client.py
database_client/models.py
middleware/primary_resource_logic/agencies.py
middleware/primary_resource_logic/proposals_logic.py
middleware/schema_and_dto_logic/primary_resource_dtos/agencies_dtos.py
middleware/schema_and_dto_logic/primary_resource_schemas/agencies_base_schemas.py
resources/Agencies.py
resources/Proposals.py
resources/endpoint_schema_config.py
tests/helper_scripts/helper_classes/RequestValidator.py
tests/helper_scripts/helper_classes/TestDataCreatorFlask.py
tests/helper_scripts/helper_functions_complex.py
tests/integration/test_agencies.py
tests/integration/test_proposals.py
tests/integration/test_typeahead_suggestions.py
tests/test_database.py
utilities/namespace.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/693#issuecomment-2764646452
* Create `/proposals/agencies` endpoint, allowing any user to submit a proposal for a new agency
* Add `creator_user_id` column to `agencies` table in database
* Update `/typeahead/agencies` to only show approved agencies (previously, it was showing all agencies).
* Increase in test overhead
* Separate endpoint whose performance is distinct from others
* Otherwise, impact marginal
* New API documentation for `/proposals/agencies` endpoint

feat(app): Create `/proposals/agencies` endpoint

---

database_client/database_client.py
middleware/primary_resource_logic/data_sources_logic.py
middleware/schema_and_dto_logic/primary_resource_dtos/data_sources_dtos.py
middleware/schema_and_dto_logic/primary_resource_schemas/data_sources_base_schemas.py
resources/DataSources.py
resources/endpoint_schema_config.py
tests/helper_scripts/helper_classes/RequestValidator.py
tests/integration/test_data_sources.py

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/700
* Add standalone admin-only endpoint for rejecting data sources.
* Separate endpoint with separate performance impact
* Increase in test overhead
* New endpoint documented in API documentation

feat(api): Add `data-sources/{id}/reject` endpoint

---

.github/workflows/run_pytest.yml
Dockerfile

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/747
* Adds uv installation to run_pytest.yml and Dockerfile
* Run tests to confirm they run as expected
* This should provide a substantial boost to installation times, in both the yaml file and the Dockerfile
* No change to documentation

Add uv to run_pytest.yml and Dockerfile

---

db/client/helpers.py
pyproject.toml
uv.lock

* Attempts to address https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/795 by strictly limiting the number of concurrent connections the pool is permitted to manage.
* Sets a pool size of 5, with an maximum overflow of 5 additional connections, down from an overflow of 10 which is the default, [per SQLAlchemy documentation](https://docs.sqlalchemy.org/en/20/core/pooling.html#sqlalchemy.pool.QueuePool).
* Impact to be determined.

mc_pool_size

---

alembic/versions/2025_07_05_1439-9689f73c0938_add_check_for_approval_status_and_.py
db/queries/instantiations/data_sources/post/single.py
middleware/primary_resource_logic/data_sources.py
tests/helper_scripts/helper_classes/RequestValidator.py
tests/helper_scripts/helper_classes/test_data_creator/db_client_/core.py
tests/integration/data_sources/put/test_approve_without_record_id.py
tests/integration/data_sources/put/test_basic.py

* https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/323
* Updates `/data-sources/{id}` `PUT` logic such that attempts to change approval status to `approved` without the `record_type` being set will yield a specific error.
* Additional test added to test for this logic.

Add logic for preventing approval of data sources with null record types

---

CONTRIBUTING.md
middleware/primary_resource_logic/data_requests_/post.py
middleware/primary_resource_logic/data_sources.py
tests/integration/data_sources/test_post.py
tests/integration/test_data_requests.py

Fixes
https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/813
Description
References a new envar to determine if "ops notifications" are on. I already added the envar on prod and dev.
I wasn't positive where to modify the logic—this could be gated at other points (turning off all mailgun notifications, for example) but I decided to limit each notification individually, rather than accidentally turning off future notifications in a confusing way.
Testing
I wasn't sure how to test this locally, and my local env is not working. Perhaps we could change the envar on dev and see?

Tweak ops notifications

---

endpoints/instantiations/locations_/locations.py

* Addresses DS side of https://github.com/Police-Data-Accessibility-Project/data-source-manager/issues/423
* Deprecates various endpoints and eliminates their tests:
- `/agencies` `POST`
- `/agencies/{resource_id}` `PUT`
- `/agencies/{resource_id}` `DELETE`
- `/agencies/{resouce_id}/locations/{location_id}` `POST`
- `/agencies/{resouce_id}/locations/{location_id}` `DELETE`
- `/locations/{location_id}` `PUT`
* Run tests and confirm all pass as expected
* Decrease in test overhead 
* Above endpoints now marked as deprecated
* No breaking changes, but support for above endpoints is ending, and endpoints will eventually be removed.

Finish deprecating endpoints
